### PR TITLE
Adds support for Travis CI

### PR DESCRIPTION
**Pull request by frankcash**
Adds `.travis.yml`

### CODE REVIEW

**Comment by frankcash** [comment]
This can serve to help solve part of #10 although it doesn't actually add tests, it does add ability to run on Travis.

**Comment by raimohanska** [comment]
As it says on Readme, this library is no longer maintained. Feel free to fork it though. Or try the suggested bacon.jquery lib. Happy hacking!

**Comment by frankcash** [comment]
I feel so foolish now, must've looked over that :disappointed:

**Comment by raimohanska** [comment]
Please don't! I'm sorry if a lot of your time was wasted though. Bacon.JQuery should be a pretty easy swap.

**Pull request closed without merging**
